### PR TITLE
Initiating go version of cert_server

### PR DESCRIPTION
**Pull request by jonghoonkwon**
For new ScionLab, it would be good time to use the new certificate server code written by go.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-utilities/6)

### CODE REVIEW

**Review by hausheer — DISMISSED** [review]
I applied the change. 

I get the following error:

`tail -f ../../scionproto/scion/logs/cs1-12-1.OUT   `
`bash: /home/scion/go/src/github.com/scionproto/scion/bin/cert_server: No such file or directory`

In my case the file in `scion/bin` is called `cert_srv` instead.

Unfortunately, I haven't been able to look through the code in detail.

**Comment by jonghoonkwon** [comment]
The executable filename has been changed to `cert_srv`. You can try out it again.

**Comment by mlegner** [comment]
I get an error 
```
Unable to load key
    open gen/ISD1/AS1003/cs1-1003-1/keys/as-sig.key: no such file or directory
```
I guess there is some problem with the extension `.key` and `.seed`.
Otherwise it looks fine to me.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-utilities/6#-:-L61ADKHRxH77PHPr_NO:btlzypp)*

**Comment by mlegner** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-utilities/6)*

**Comment by jonghoonkwon** [comment]
The new cs instance written by go requires both of `as_sig.key` and `as_sig.seed`.
To address the new key generation, I'm going to create another PR right after merging this PR.
Thanks for the comments.

**Pull request merged**
