### PR TITLE
Create all the new keys required for a new cert service

### PR DESCRIPTION
**Pull request by jonghoonkwon**
A new certificate service was introduced and `local_config_util.py` has been updated to maintain all new key information.
This PR is required to change other projects related to 'Scion-utilities'.

---
This change is [Reviewable](https://reviewable.io/reviews/netsec-ethz/scion-utilities/8)

### CODE REVIEW

**Comment by hausheer** [comment]
I tested the PR and I am getting the following error when trying to generate a local gen:

  File "/home/scion/go/src/github.com/netsec-ethz/scion-coord/python/local_gen.py", line 47, in <module>
    from local_config_util import (
  File "/home/scion/go/src/github.com/netsec-ethz/scion-coord/sub/util/local_config_util.py", line 32, in <module>
    from lib.crypto.asymcrypto import (
ImportError: cannot import name 'get_core_sig_key_file_path'

**Comment by mlegner** [comment]
As far as I understand, this PR depends on https://github.com/scionproto/scion/pull/1414 where this function (and some others) are added.

**Comment by hausheer** [comment]
I understand. I will update to the newest scion commit then and try again.

**Comment by jonghoonkwon** [comment]
@hausheer  It requires scionproto/scion#1414 which is under codereview and not merged yet.
You can test out by temporary branching the #1414 as follows:

git checkout -b oncilla-conf_sep_sign_key
git pull git@github.com:oncilla/scion.git conf-sep-sign-key

**Comment by juagargi** [comment]
:lgtm:
We are going to temporarily use this branch in the coordinator to be able to correctly sign things, as the infrastructure is running the branch from scionproto 1414 already.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/netsec-ethz/scion-utilities/8#-:-L6MyWe87R_n2Vuk2rpa:b-lgtzc5)*

**Review by hausheer — APPROVED** [review]
I noticed that https://github.com/scionproto/scion/pull/1414 has been merged in the meantime and this indeed solved my get_core_sig_key_file_path import error. So from my side this is good to go.

**Comment by hausheer** [comment]
We should apply https://github.com/scionproto/scion/pull/1414 to the scionlab branch of netsec-scion

**Pull request merged**
